name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rokit
        run: |
          curl -sSf https://raw.githubusercontent.com/rojo-rbx/rokit/main/scripts/install.sh | bash
          echo "$HOME/.rokit/bin" >> "$GITHUB_PATH"

      - name: Trust tools
        run: |
          rokit trust rojo-rbx/rojo
          rokit trust JohnnyMorganz/StyLua
          rokit trust Kampfkarren/selene
          rokit trust lune-org/lune
          rokit trust UpliftGames/wally
          rokit trust JohnnyMorganz/luau-lsp

      - name: Install tools
        run: rokit install

      - name: Run checks
        run: make check
